=== VijayEluri/TC/Development/file_format_validator_1.0.0_dev_dist/docs/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="lineTypeName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="header"/>
      <xs:enumeration value="data"/>
      <xs:enumeration value="footer"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="fieldTypeName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Integer"/>
      <xs:enumeration value="BigDecimal"/>
      <xs:enumeration value="Date"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="operatorName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="equal"/>
      <xs:enumeration value="notEqual"/>
      <xs:enumeration value="lessThan"/>
      <xs:enumeration value="greaterThan"/>
      <xs:enumeration value="lessOrEqual"/>
      <xs:enumeration value="greaterOrEqual"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="yesNo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="3" name="lineType">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="extractor" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="field">
                      <xs:complexType>
                        <xs:attribute name="startPos" type="xs:positiveInteger"
                                      use="required" />
                        <xs:attribute name="endPos" type="xs:positiveInteger"
                                      use="required" />
                        <xs:attribute name="trim" type="yesNo" use="optional"
                                      default="yes" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="required" />
                  <xs:attribute name="separator" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element name="validators" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="validator">
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="fieldIndex" type="xs:positiveInteger"
                                      use="optional" />
                        <xs:attribute name="pattern" type="xs:string" use="optional" />
                        <xs:attribute name="operator" type="operatorName" use="optional" />
                        <xs:attribute name="value" type="xs:string" use="optional" />
                        <xs:attribute name="fieldType" type="fieldTypeName" use="optional" />
                        <xs:attribute name="format" type="xs:string" use="optional" />
                        <xs:attribute name="skipIfEmpty" type="yesNo" use="optional"
                                      default="no" />
                        <xs:attribute name="fieldIndex1" type="xs:positiveInteger"
                                      use="optional" />
                        <xs:attribute name="fieldIndex2" type="xs:positiveInteger"
                                      use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="type" type="lineTypeName" use="required" />
            <xs:attribute name="pattern" type="xs:string" use="optional" />
            <xs:attribute name="num" type="xs:positiveInteger" use="optional" />
            <xs:attribute name="minNum" type="xs:nonNegativeInteger" use="optional" />
            <xs:attribute name="maxNum" type="xs:positiveInteger" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="formatName" type="xs:string" use="required" />
      <xs:attribute name="ignoredLinePattern" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== VijayEluri/TC/Development/file_format_validator_1.0.0_dev_dist/docs/fixed_config.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config.xsd"
        formatName="Sample Fixed Column Length Format"
        ignoredLinePattern="\*.*">
  <lineType type="header" pattern="H .*" num="1">
    <extractor type="fixed">
      <field startPos="3" endPos="7" trim="no"/>
      <field startPos="9" endPos="9"/>
      <field startPos="11" endPos="13"/>
      <field startPos="15" endPos="33"/>
      <field startPos="35" endPos="37"/>
    </extractor>
    <validators>
      <validator type="regex" fieldIndex="1" pattern="[0-9]{5}"/>
      <validator type="regex" fieldIndex="2" pattern="[D|N]"/>
      <validator type="numberComparison" fieldIndex="3"
                 operator="greaterOrEqual" value="123"/>
      <validator type="fieldType" fieldIndex="4" fieldType="Date"
                 format="yyyy-MM-dd-HH:mm:ss"/>
      <validator type="regex" fieldIndex="5" pattern="[A-Z]{3}"/>
    </validators>
  </lineType>
  <lineType type="data" pattern="D .*" minNum="1">
    <extractor type="fixed">
      <field startPos="3" endPos="6"/>
      <field startPos="8" endPos="11"/>
      <field startPos="16" endPos="19"/>
      <field startPos="24" endPos="27"/>
      <field startPos="29" endPos="29"/>
      <field startPos="31" endPos="42"/>
      <field startPos="44" endPos="53"/>
      <field startPos="55" endPos="57"/>
      <field startPos="59" endPos="61"/>
    </extractor>
    <validators>
      <validator type="fieldType" fieldIndex="1" fieldType="Integer"/>
      <validator type="fieldType" fieldIndex="2" fieldType="Integer"
                 skipIfEmpty="yes"/>
      <validator type="fieldType" fieldIndex="3" fieldType="Integer"/>
      <validator type="fieldType" fieldIndex="4" fieldType="Integer"
                 skipIfEmpty="yes"/>
      <validator type="regex" fieldIndex="5" pattern="[F|U]"/>
      <validator type="regex" fieldIndex="6" pattern="[0-9]{9}\.[0-9]{2}"/>
      <validator type="dateComparison" fieldIndex="7" operator="greaterThan"
                 value="2009-01-01" format="yyyy-MM-dd"/>
      <validator type="twoNumberFieldsComparison" fieldIndex1="9" fieldIndex2="8"
                 operator="greaterThan"/>
    </validators>
  </lineType>
  <lineType type="footer" pattern="T .*" num="1">
    <extractor type="fixed">
      <field startPos="3" endPos="7"/>
      <field startPos="9" endPos="16"/>
      <field startPos="18" endPos="32"/>
    </extractor>
    <validators>
      <validator type="regex" fieldIndex="1" pattern="[0-9]{5}"/>
      <validator type="regex" fieldIndex="2" pattern="[0-9]{8}"/>
      <validator type="regex" fieldIndex="3" pattern="[0-9]{12}\.[0-9]{2}"/>
    </validators>
  </lineType>
</config>

=== VijayEluri/TC/Development/file_format_validator_1.0.0_dev_dist/docs/csv_config.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config.xsd"
        formatName="Sample CSV Format"
        ignoredLinePattern="#.*">
  <lineType type="header" num="1">
    <extractor type="csv" />
    <validators>
      <validator type="regex" fieldIndex="1" pattern="ID"/>
      <validator type="regex" fieldIndex="2" pattern="START"/>
      <validator type="regex" fieldIndex="3" pattern="END"/>
      <validator type="regex" fieldIndex="4" pattern="CODE"/>
    </validators>
  </lineType>
  <lineType type="data" minNum="1">
    <extractor type="csv" />
    <validators>
      <validator type="fieldType" fieldIndex="1" fieldType="Integer"/>
      <validator type="numberComparison" fieldIndex="1"
                 operator="greaterThan" value="0"/>
      <validator type="fieldType" fieldIndex="2" fieldType="Integer"/>
      <validator type="fieldType" fieldIndex="3" fieldType="Integer"/>
      <validator type="twoNumberFieldsComparison" fieldIndex1="3" fieldIndex2="2"
                 operator="greaterOrEqual"/>
      <validator type="regex" fieldIndex="4" pattern="[A-Z]{3}[0-9]{3}"/>
    </validators>
  </lineType>
</config>
